
// Codigo del ejercicio
// console.log('ü•á Primero');

// setTimeout(() => {
//     console.log('üïê Timeout 1');
//     Promise.resolve().then(() => console.log('ü§î Promesa dentro de timeout'));
// }, 0);

// Promise.resolve().then(() => {
//     console.log('‚ú® Promesa 1');
//     setTimeout(() => console.log('‚è∞ Timeout dentro de promesa'), 0);
// });

// Promise.resolve().then(() => console.log('üí´ Promesa 2'));
// setTimeout(() => console.log('üïë Timeout 2'), 0);

// console.log('ü•à Segundo');


console.log('ü•á Primero');

setTimeout(() => {
    console.log('üïê Timeout 1');
    Promise.resolve().then(() => {
        console.log('ü§î Promesa dentro de timeout');
        return Promise.reject('‚ùå Promesa rechazada dentro de timeout');
    }).catch(err => console.log(err));
}, 0);

Promise.resolve()
    .then(async () => {
        console.log('‚ú® Promesa 1');
        setTimeout(() => console.log('‚è∞ Timeout dentro de promesa'), 0);
        await Promise.resolve();
        console.log('üåü Async dentro de Promesa 1');
    }).catch(err => console.log('Error:', err));

Promise.resolve()
    .then(() => console.log('üí´ Promesa 2'));
    setTimeout(() => console.log('üïë Timeout 2'), 0);
    console.log('ü•à Segundo');

(async () => {
    try {
        await Promise.reject('‚ùå Promesa rechazada con async/await');
    } catch (err) {
        console.log(err);
    }
})();
